language: objective-c
osx_image: xcode7.3
rvm: 2.2.5

cache:
- bundler 

before_install:
- bundle install
- bundle exec pod repo update --silent

install: true

script:
- bundle exec pod lib lint --allow-warnings
- xctool -project UITableView+Cache.xcodeproj -scheme 'UITableView+Cache' -sdk iphonesimulator build
