language: objective-c

osx_image: xcode7.1

before_install:

    - export LANG=en_US.UTF-8
    - env
    - locale
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - pod --version
    - pod setup --silent > /dev/null
    - pod repo update --silent

script:

    - pod lib lint --allow-warnings
    - xctool -project UITableView+Cache.xcodeproj -scheme 'UITableView+Cache' -sdk iphonesimulator build
